# Generated by Django 3.2.7 on 2021-11-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EMSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=150)),
                ('av_slots', models.CharField(max_length=150)),
                ('cap', models.CharField(default='', max_length=150)),
                ('serv', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('slots', models.CharField(max_length=150)),
                ('event_type', models.CharField(max_length=150)),
                ('capacity', models.CharField(max_length=50)),
                ('services', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EMSapp.customers')),
            ],
        ),
    ]
