# Generated by Django 3.2.7 on 2021-11-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSapp', '0003_bookings_cust_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='location',
            field=models.CharField(default='Mumbai,Maharashtra', max_length=500),
        ),
    ]
